### ISSUE TITLE
layershifter/tld-extract is deprecated

### ISSUE THREAD

**Issue by nclsHart** [devnix/mailcheck#2]
There is 2 warnings while installing this lib:

```
Package layershifter/tld-support is abandoned, you should avoid using it. No replacement was suggested.
Package layershifter/tld-extract is abandoned, you should avoid using it. No replacement was suggested.
```

As said on tld-extract [README](https://github.com/layershifter/TLDExtract), it's recommended to use https://github.com/jeremykendall/php-domain-parser instead.

**Comment by devnix** [comment]
Will take a look!

**Comment by hotmeteor** [comment]
@devnix Is this something you can tag and release?

**Comment by devnix** [comment]
@hotmeteor This is still not implemented, and I will be very busy for the next weeks. I could merge a PR if you want to contribute and tag it 😄

**Comment by hotmeteor** [comment]
I'm happy to, and have already started, but this is looking like there's probably going to be some big changes.

**Comment by hotmeteor** [comment]
@devnix Ok turns out it wasn't so bad once I bailed on `jeremykendall/php-domain-parser`. The `utopia-php/domains` parser did exactly what we needed.

**Comment by devnix** [comment]
New tag released, thank you so much for your contribution @hotmeteor!
